name: Pull request workflow

on:
  pull_request:

jobs:
  validate_commits:
    name: ðŸ“– Validate commit messages
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Validate all commits from PR
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  build_and_test:
    name: ðŸ› ï¸ Build and test
    needs: validate_commits
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read

  canary_release:
    name: ðŸ¥ Canary release
    needs:
      - build_and_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Write release status
        id: release_status
        run: |
          pnpm changeset status --since origin/main --output release.json 2> /dev/null || true
          HAS_RELEASE="$(node scripts/has-release-prepared.cjs)"
          if [ -f release.json ]; then
            cat release.json
          fi

          echo ""
          echo "has release $HAS_RELEASE"
          echo "has-changeset=$HAS_RELEASE" >> $GITHUB_OUTPUT

      - name: Build packages
        if: ${{ steps.release_status.outputs.has-changeset == 'true' }}
        run: pnpm build:packages

      - name: Release packages
        if: ${{ steps.release_status.outputs.has-changeset == 'true' }}
        run: |
          pnpm changeset version --snapshot canary
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          node scripts/update-package-readmes.cjs
          pnpm changeset publish --tag canary
          git tag -l
          rm .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update PR
        if: ${{ steps.release_status.outputs.has-changeset == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: node scripts/update-canary-release-pr-body.cjs

  pr_checks_passed:
    name: âœ… PR checks passed
    needs: canary_release
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: echo "PR checks passed"
